version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - /root/www/:/www/
    ports:
      - "80:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    